# Generated by Django 4.2.1 on 2023-05-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ID',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
