# Generated by Django 4.2.1 on 2023-05-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0004_address_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='House_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.TextField()),
            ],
        ),
    ]
